### ISSUE TITLE
Non-functional classifiers

### ISSUE THREAD

**Issue by James-Large** [uea-machine-learning/tsml#159]
Based on attempts to add these to the integration testing stuff (#158) using italypowerdemand fold 0, the following classifiers seem to have problems:

* LPS - despite setting seed, is not deterministic, should be simple fix but not looked into class
* HiveCote (including Tony's changes in response to issue #153) - despite setting seed, is not deterministic. Probably the seed is simply not being propagated to the base classifiers
* FlatCote ((including Tony's changes in response to issue #151) gets error
```
FlatCote evaluation on ItalyPowerDemand FAILED
java.lang.NullPointerException
	at timeseriesweka.filters.shapelet_transforms.ShapeletTransform.roundRobinData(ShapeletTransform.java:1197)
	at timeseriesweka.filters.shapelet_transforms.ShapeletTransform.initDataSource(ShapeletTransform.java:547)
	at timeseriesweka.filters.shapelet_transforms.ShapeletTransform.trainShapelets(ShapeletTransform.java:521)
	at timeseriesweka.filters.shapelet_transforms.ShapeletTransform.process(ShapeletTransform.java:509)
	at weka_extras.classifiers.ensembles.AbstractEnsemble.classifyInstanceByConstituents(AbstractEnsemble.java:1021)
	at timeseriesweka.classifiers.hybrids.FlatCote.classifyInstance(FlatCote.java:151)
	at timeseriesweka.classifiers.hybrids.FlatCote.distributionForInstance(FlatCote.java:137)
	at evaluation.evaluators.SingleTestSetEvaluator.evaluate(SingleTestSetEvaluator.java:75)
	at evaluation.evaluators.SingleTestSetEvaluator.evaluate(SingleTestSetEvaluator.java:100)
	at utilities.ClassifierTools.testUtils_evalOnIPD(ClassifierTools.java:715)
	at experiments.BasicReproductionTests.generateExpectedResult(BasicReproductionTests.java:345)
	at experiments.BasicReproductionTests.generateMissingExpectedResults(BasicReproductionTests.java:307)
	at experiments.BasicReproductionTests.main(BasicReproductionTests.java:495)
```
* TSBF results in exception (after 8 minutes...)
```
TSBF evaluation on ItalyPowerDemand FAILED
Exception in thread "main" java.lang.NullPointerException
	at weka_extras.classifiers.tuned.TunedRandomForest$EnhancedBagging.mergeBaggers(TunedRandomForest.java:571)
	at weka_extras.classifiers.tuned.TunedRandomForest.addTrees(TunedRandomForest.java:550)
	at timeseriesweka.classifiers.interval_based.TSBF.buildClassifier(TSBF.java:501)
	at timeseriesweka.classifiers.interval_based.TSBF.buildClassifier(TSBF.java:439)
	at evaluation.evaluators.SingleTestSetEvaluator.evaluate(SingleTestSetEvaluator.java:97)
	at utilities.ClassifierTools.testUtils_evalOnIPD(ClassifierTools.java:715)
	at utilities.ClassifierTools.testUtils_getIPDAcc(ClassifierTools.java:726)
	at timeseriesweka.classifiers.interval_based.TSBF.main(TSBF.java:777)
C:\Users\xmw13bzu\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 8 minutes 50 seconds)
```

**Comment by TonyBagnall** [comment]
LPS and HiveCote fixed, working on the others

**Comment by TonyBagnall** [comment]
FlatCote fixed, working on TSBF but tempted to depreciate the whole classifier, seems a bit broken ....

**Comment by TonyBagnall** [comment]
ok, have temporarily fixed TSBF, stepwise and restart features turned off. There is still an underlying problem with the contract rotation forest add trees method, but it will have to wait.
