### ISSUE TITLE
BUG: SpatialBOSS 

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/tsml#197]
when building train files, it sometimes throws this error

ERROR: java.lang.ArrayIndexOutOfBoundsException: -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at timeseriesweka.classifiers.dictionary_based.SpatialBOSS.distributionForInstance(SpatialBOSS.java:510)
	at timeseriesweka.classifiers.dictionary_based.SpatialBOSS.findEnsembleTrainAcc(SpatialBOSS.java:454)
	at timeseriesweka.classifiers.dictionary_based.SpatialBOSS.buildClassifier(SpatialBOSS.java:414)
	at development.LocalExperiments.runExperiment(LocalExperiments.java:304)
	at development.LocalExperiments.setupAndRunExperiment(LocalExperiments.java:243)
	at development.LocalExperiments.main(LocalExperiments.java:104)

**Comment by TonyBagnall** [comment]
to recreate, run on, for example. ArrowHead

**Comment by James-Large** [comment]
fixed, #201
