### ISSUE TITLE
Issue in running Ex07_HIVE_COTE_Examples.java

### ISSUE THREAD

**Issue by saifkhan-m** [uea-machine-learning/tsml#446]
I am trying to classify a time series dataset and came across HIVE-COTE as the state of the art algorithm for the classification, therefore, trying to gain some knowledge about it.

While running the example given for HIVE-COTE in file `Ex07_HIVE_COTE_Examples.java`, I am getting the following error when running basicUsage() and usageWithExperimentsClass() functions of the class.

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at weka.core.DenseInstance.setValue(DenseInstance.java:245)
	at tsml.transformers.PACF.transform(PACF.java:168)
	at tsml.transformers.Transformer.transform(Transformer.java:43)
	at tsml.classifiers.legacy.RISE.filterData(RISE.java:565)
	at tsml.classifiers.legacy.RISE.buildClassifier(RISE.java:383)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.lambda$trainModules$0(AbstractEnsemble.java:380)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.trainModules(AbstractEnsemble.java:406)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.initialiseModules(AbstractEnsemble.java:354)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.buildClassifier(AbstractEnsemble.java:882)
	at tsml.classifiers.hybrids.HIVE_COTE.buildClassifier(HIVE_COTE.java:219)
	at examples.Ex07_HIVE_COTE_Examples.basicUsage(Ex07_HIVE_COTE_Examples.java:31)
	at examples.Ex07_HIVE_COTE_Examples.main(Ex07_HIVE_COTE_Examples.java:215)`

The complete error is present in the file attached.
[error.txt](https://github.com/uea-machine-learning/tsml/files/5483295/error.txt)

And following error with setClassifiersAndThread() function:

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at weka.core.DenseInstance.setValue(DenseInstance.java:245)
	at tsml.transformers.PACF.transform(PACF.java:168)
	at tsml.transformers.Transformer.transform(Transformer.java:43)
	at tsml.classifiers.legacy.RISE.filterData(RISE.java:565)
	at tsml.classifiers.legacy.RISE.buildClassifier(RISE.java:383)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.lambda$trainModules$0(AbstractEnsemble.java:380)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.trainModules(AbstractEnsemble.java:406)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.initialiseModules(AbstractEnsemble.java:354)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.buildClassifier(AbstractEnsemble.java:882)
	at tsml.classifiers.hybrids.HIVE_COTE.buildClassifier(HIVE_COTE.java:219)
	at examples.Ex07_HIVE_COTE_Examples.basicUsage(Ex07_HIVE_COTE_Examples.java:31)
	at examples.Ex07_HIVE_COTE_Examples.main(Ex07_HIVE_COTE_Examples.java:215)`

The complete error is present in the file attached.
[error2.txt](https://github.com/uea-machine-learning/tsml/files/5483375/error2.txt)

**Comment by TonyBagnall** [comment]
hi, sorry, we are not great at monitoring this, we have few external interactions! @jasonlines did you write this or did @James-Large ?

**Comment by stevcabello** [comment]
Hi, I was having the same problem. I fixed it by doing this:

Go to the HIVE_COTE.java (located in src/main/java/tsml/classifiers/hybrids/),

and change 
import tsml.classifiers.legacy.RISE;

to 
import tsml.classifiers.interval_based.RISE;
