### ISSUE TITLE
Jar throws an exception on weka  

### ISSUE THREAD

**Issue by a-pasos-ruiz** [uea-machine-learning/tsml#454]
When running locally it works fine but executing the jar throws the following error

Exception in thread "main" java.lang.NoSuchMethodError: weka.classifiers.functions.SMO.setBuildLogisticModels(Z)V
	at machine_learning.classifiers.ensembles.CAWPE.setupDefaultEnsembleSettings(CAWPE.java:139)
	at machine_learning.classifiers.ensembles.AbstractEnsemble.<init>(AbstractEnsemble.java:148)
	at machine_learning.classifiers.ensembles.CAWPE.<init>(CAWPE.java:112)
	at tsml.ClassifierLists.setMultivariate(ClassifierLists.java:430)
	at experiments.ClassifierLists.setClassifier(ClassifierLists.java:817)
	at experiments.Experiments.setupAndRunExperiment(Experiments.java:222)
	at experiments.Experiments.main(Experiments.java:140).classifiers.multivariate.MultivariateShapeletTransformClassifier.configureDefaultEnsemble(MultivariateShapeletTransformClassifier.java:210)
	at tsml.classifiers.multivariate.MultivariateShapeletTransformClassifier.<init>(MultivariateShapeletTransformClassifier.java:107)
	at experiments

**Comment by TonyBagnall** [comment]
this was because of the double weka I assume, should be fixed
